"""test custom operation

Revision ID: 49454cab6435
Revises: 75561a88aaf0
Create Date: 2026-04-08 00:05:07.280140

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49454cab6435"
down_revision: Union[str, None] = "75561a88aaf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_policy(
        table_name="items",
        policy_name="items_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="((owner_id = (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    op.create_policy(
        table_name="items",
        policy_name="items_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="owner_id = CAST(current_setting('rls.account_id', true) AS INTEGER)",
    )  # type: ignore
    op.drop_policy(
        table_name="items",
        policy_name="items_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="PERMISSIVE",
        expr="((owner_id = (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    op.create_policy(
        table_name="items",
        policy_name="items_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="PERMISSIVE",
        expr="owner_id = CAST(current_setting('rls.account_id', true) AS INTEGER)",
    )  # type: ignore
    op.drop_policy(
        table_name="items",
        policy_name="items_greater_than_accountid_policy_select_policy_1",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="((owner_id > (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    op.create_policy(
        table_name="items",
        policy_name="items_greater_than_accountid_policy_select_policy_1",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="owner_id > CAST(current_setting('rls.account_id', true) AS INTEGER)",
    )  # type: ignore
    op.drop_policy(
        table_name="items",
        policy_name="items_smaller_than_or_equal_accountid_policy_all_policy_2",
        cmd="ALL",
        definition="PERMISSIVE",
        expr="((owner_id <= (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    op.create_policy(
        table_name="items",
        policy_name="items_smaller_than_or_equal_accountid_policy_all_policy_2",
        cmd="ALL",
        definition="PERMISSIVE",
        expr="owner_id <= CAST(current_setting('rls.account_id', true) AS INTEGER)",
    )  # type: ignore
    op.drop_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="((id = (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    op.create_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="id = CAST(current_setting('rls.account_id', true) AS INTEGER)",
    )  # type: ignore
    op.drop_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="PERMISSIVE",
        expr="((id = (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    op.create_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="PERMISSIVE",
        expr="id = CAST(current_setting('rls.account_id', true) AS INTEGER)",
    )  # type: ignore
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="PERMISSIVE",
        expr="id = CAST(current_setting('rls.account_id', true) AS INTEGER)",
    )  # type: ignore
    op.create_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="PERMISSIVE",
        expr="((id = (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    op.drop_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="id = CAST(current_setting('rls.account_id', true) AS INTEGER)",
    )  # type: ignore
    op.create_policy(
        table_name="users",
        policy_name="users_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="((id = (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    op.drop_policy(
        table_name="items",
        policy_name="items_smaller_than_or_equal_accountid_policy_all_policy_2",
        cmd="ALL",
        definition="PERMISSIVE",
        expr="owner_id <= CAST(current_setting('rls.account_id', true) AS INTEGER)",
    )  # type: ignore
    op.create_policy(
        table_name="items",
        policy_name="items_smaller_than_or_equal_accountid_policy_all_policy_2",
        cmd="ALL",
        definition="PERMISSIVE",
        expr="((owner_id <= (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    op.drop_policy(
        table_name="items",
        policy_name="items_greater_than_accountid_policy_select_policy_1",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="owner_id > CAST(current_setting('rls.account_id', true) AS INTEGER)",
    )  # type: ignore
    op.create_policy(
        table_name="items",
        policy_name="items_greater_than_accountid_policy_select_policy_1",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="((owner_id > (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    op.drop_policy(
        table_name="items",
        policy_name="items_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="PERMISSIVE",
        expr="owner_id = CAST(current_setting('rls.account_id', true) AS INTEGER)",
    )  # type: ignore
    op.create_policy(
        table_name="items",
        policy_name="items_equal_to_accountid_policy_update_policy_0",
        cmd="UPDATE",
        definition="PERMISSIVE",
        expr="((owner_id = (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    op.drop_policy(
        table_name="items",
        policy_name="items_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="owner_id = CAST(current_setting('rls.account_id', true) AS INTEGER)",
    )  # type: ignore
    op.create_policy(
        table_name="items",
        policy_name="items_equal_to_accountid_policy_select_policy_0",
        cmd="SELECT",
        definition="PERMISSIVE",
        expr="((owner_id = (COALESCE(current_setting('rls.account_id'::text), ''::text))::integer) OR ((NULLIF(current_setting('rls.bypass_rls'::text, true), ''::text))::boolean = true))",
    )  # type: ignore
    # ### end Alembic commands ###
