on:
    push:
        branches: [main]

jobs:
    quality-test:
        name: Test/Quality
        uses: DelfinaCare/rls/.github/workflows/quality.yml@main

    release:
        needs: quality-test
        name: Release
        uses: DelfinaCare/rls/.github/workflows/release.yml@main
