name: Code Quality Test

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: 3.12
      - name: Install
        run: pip install -e ".[dev]"
      - name: Run Mypy
        run: mypy rls/

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            cache: pip
            python-version: 3.12
      - name: Install dependencies
        run: pip install -e ".[dev]"
      - name: Run unit tests
        env:
            PYTHONPATH: "${{ github.workspace }}/test"
        run: |
          python3 -m unittest test/test_alembic.py && python3 -m unittest test/test_rls.py