name: Python Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            cache: pip
            python-version: 3.12
      - name: Install dependencies
        run: pip install -e ".[dev]"
      - name: Run unit tests
        env:
            PYTHONPATH: "${{ github.workspace }}/test"
        run: |
          python3 -m unittest test/test_alembic.py && python3 -m unittest test/test_rls.py